/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ArchivedRouteImport } from './routes/archived'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as AccountSettingsRouteImport } from './routes/account/settings'
import { Route as AccountEditAccountRouteImport } from './routes/account/editAccount'
import { Route as AccountDeleteAccountRouteImport } from './routes/account/deleteAccount'
import { Route as AccountAchievementsRouteImport } from './routes/account/achievements'
import { Route as AccountSettingsQuickFiltersRouteImport } from './routes/account/settings/quick-filters'
import { Route as AccountSettingsNotificationsRouteImport } from './routes/account/settings/notifications'
import { Route as AccountSettingsAboutRouteImport } from './routes/account/settings/about'

const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchivedRoute = ArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/account/settings',
  path: '/account/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountEditAccountRoute = AccountEditAccountRouteImport.update({
  id: '/account/editAccount',
  path: '/account/editAccount',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountDeleteAccountRoute = AccountDeleteAccountRouteImport.update({
  id: '/account/deleteAccount',
  path: '/account/deleteAccount',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountAchievementsRoute = AccountAchievementsRouteImport.update({
  id: '/account/achievements',
  path: '/account/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSettingsQuickFiltersRoute =
  AccountSettingsQuickFiltersRouteImport.update({
    id: '/quick-filters',
    path: '/quick-filters',
    getParentRoute: () => AccountSettingsRoute,
  } as any)
const AccountSettingsNotificationsRoute =
  AccountSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AccountSettingsRoute,
  } as any)
const AccountSettingsAboutRoute = AccountSettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AccountSettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archived': typeof ArchivedRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/todos': typeof TodosRoute
  '/account/achievements': typeof AccountAchievementsRoute
  '/account/deleteAccount': typeof AccountDeleteAccountRoute
  '/account/editAccount': typeof AccountEditAccountRoute
  '/account/settings': typeof AccountSettingsRouteWithChildren
  '/account/': typeof AccountIndexRoute
  '/account/settings/about': typeof AccountSettingsAboutRoute
  '/account/settings/notifications': typeof AccountSettingsNotificationsRoute
  '/account/settings/quick-filters': typeof AccountSettingsQuickFiltersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archived': typeof ArchivedRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/todos': typeof TodosRoute
  '/account/achievements': typeof AccountAchievementsRoute
  '/account/deleteAccount': typeof AccountDeleteAccountRoute
  '/account/editAccount': typeof AccountEditAccountRoute
  '/account/settings': typeof AccountSettingsRouteWithChildren
  '/account': typeof AccountIndexRoute
  '/account/settings/about': typeof AccountSettingsAboutRoute
  '/account/settings/notifications': typeof AccountSettingsNotificationsRoute
  '/account/settings/quick-filters': typeof AccountSettingsQuickFiltersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archived': typeof ArchivedRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/todos': typeof TodosRoute
  '/account/achievements': typeof AccountAchievementsRoute
  '/account/deleteAccount': typeof AccountDeleteAccountRoute
  '/account/editAccount': typeof AccountEditAccountRoute
  '/account/settings': typeof AccountSettingsRouteWithChildren
  '/account/': typeof AccountIndexRoute
  '/account/settings/about': typeof AccountSettingsAboutRoute
  '/account/settings/notifications': typeof AccountSettingsNotificationsRoute
  '/account/settings/quick-filters': typeof AccountSettingsQuickFiltersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archived'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/todos'
    | '/account/achievements'
    | '/account/deleteAccount'
    | '/account/editAccount'
    | '/account/settings'
    | '/account/'
    | '/account/settings/about'
    | '/account/settings/notifications'
    | '/account/settings/quick-filters'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archived'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/todos'
    | '/account/achievements'
    | '/account/deleteAccount'
    | '/account/editAccount'
    | '/account/settings'
    | '/account'
    | '/account/settings/about'
    | '/account/settings/notifications'
    | '/account/settings/quick-filters'
  id:
    | '__root__'
    | '/'
    | '/archived'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/todos'
    | '/account/achievements'
    | '/account/deleteAccount'
    | '/account/editAccount'
    | '/account/settings'
    | '/account/'
    | '/account/settings/about'
    | '/account/settings/notifications'
    | '/account/settings/quick-filters'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchivedRoute: typeof ArchivedRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  TodosRoute: typeof TodosRoute
  AccountAchievementsRoute: typeof AccountAchievementsRoute
  AccountDeleteAccountRoute: typeof AccountDeleteAccountRoute
  AccountEditAccountRoute: typeof AccountEditAccountRoute
  AccountSettingsRoute: typeof AccountSettingsRouteWithChildren
  AccountIndexRoute: typeof AccountIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archived': {
      id: '/archived'
      path: '/archived'
      fullPath: '/archived'
      preLoaderRoute: typeof ArchivedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/settings': {
      id: '/account/settings'
      path: '/account/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/editAccount': {
      id: '/account/editAccount'
      path: '/account/editAccount'
      fullPath: '/account/editAccount'
      preLoaderRoute: typeof AccountEditAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/deleteAccount': {
      id: '/account/deleteAccount'
      path: '/account/deleteAccount'
      fullPath: '/account/deleteAccount'
      preLoaderRoute: typeof AccountDeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/achievements': {
      id: '/account/achievements'
      path: '/account/achievements'
      fullPath: '/account/achievements'
      preLoaderRoute: typeof AccountAchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/settings/quick-filters': {
      id: '/account/settings/quick-filters'
      path: '/quick-filters'
      fullPath: '/account/settings/quick-filters'
      preLoaderRoute: typeof AccountSettingsQuickFiltersRouteImport
      parentRoute: typeof AccountSettingsRoute
    }
    '/account/settings/notifications': {
      id: '/account/settings/notifications'
      path: '/notifications'
      fullPath: '/account/settings/notifications'
      preLoaderRoute: typeof AccountSettingsNotificationsRouteImport
      parentRoute: typeof AccountSettingsRoute
    }
    '/account/settings/about': {
      id: '/account/settings/about'
      path: '/about'
      fullPath: '/account/settings/about'
      preLoaderRoute: typeof AccountSettingsAboutRouteImport
      parentRoute: typeof AccountSettingsRoute
    }
  }
}

interface AccountSettingsRouteChildren {
  AccountSettingsAboutRoute: typeof AccountSettingsAboutRoute
  AccountSettingsNotificationsRoute: typeof AccountSettingsNotificationsRoute
  AccountSettingsQuickFiltersRoute: typeof AccountSettingsQuickFiltersRoute
}

const AccountSettingsRouteChildren: AccountSettingsRouteChildren = {
  AccountSettingsAboutRoute: AccountSettingsAboutRoute,
  AccountSettingsNotificationsRoute: AccountSettingsNotificationsRoute,
  AccountSettingsQuickFiltersRoute: AccountSettingsQuickFiltersRoute,
}

const AccountSettingsRouteWithChildren = AccountSettingsRoute._addFileChildren(
  AccountSettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchivedRoute: ArchivedRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  TodosRoute: TodosRoute,
  AccountAchievementsRoute: AccountAchievementsRoute,
  AccountDeleteAccountRoute: AccountDeleteAccountRoute,
  AccountEditAccountRoute: AccountEditAccountRoute,
  AccountSettingsRoute: AccountSettingsRouteWithChildren,
  AccountIndexRoute: AccountIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
